version: '2'

services:
  app:
    image: 'docker-browser:latest'
    ports:
      - "8086:8086"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-browser-container:5432/browser
      - SPRING_DATASOURCE_USERNAME=browser
      - SPRING_DATASOURCE_PASSWORD=browser@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:9.6-alpine'
    container_name: psql-browser-container
    environment:
      - POSTGRES_USER=browser
      - POSTGRES_PASSWORD=browser@123